spring.application.name=gestionturnos

# =========================================
# BASE DE DATOS H2 EN ARCHIVO
# =========================================
spring.datasource.url=jdbc:h2:file:./data/gestionturnosdb;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# =========================================
# JPA / HIBERNATE
# =========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# =========================================
# CONSOLA H2
# =========================================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# =========================================
# THYMELEAF
# =========================================
spring.thymeleaf.cache=false

# =========================================
# INICIALIZACIÓN SQL
# =========================================
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:org/springframework/batch/core/schema-h2.sql
spring.sql.init.data-locations=classpath:data.sql
spring.sql.init.continue-on-error=true

# =========================================
# SPRING BATCH
# =========================================
spring.batch.jdbc.initialize-schema=never
spring.batch.job.enabled=false

# =========================================
# SERVIDOR
# =========================================
server.port=8080